# Estas propiedades son para el perfil por "dev"

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/sfg_dev?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: sfg_dev_user
    password: guru
  jpa:
    hibernate:
      ddl-auto: validate # Indicamos a Hibernate que verifique o compruebe el esquema de la base de datos para que sea el esperado, es decir, si las tablas y sus relacioes están creadas en la base de datos. No es buena idea que en Producción que Hibernate cree o modifique elementos de la base de datos de manera automática. Por esta razón, sólo le indicamos que verifique y no ponemos, por ejemplo "create" o "create-drop"
    database-platform: org.hibernate.dialect.MySQL8Dialect
    database: mysql
    show-sql: true # En el entorno de Desarrollo queremos visualizar por consola las consultas SQL que se realizan sobre la base de datos
    # Estas propiedades de abajo de Javax son para generar automáticamente el script "guru_database_create.sql" en la raíz del proyecto con las sentencias SQL para crear las tablas y sus relaciones a partir de una fuente de metadatos obtenida de las clases entidad de nuestro dominio(clases entidad que están en el paquete "guru.springframework.spring5recipeapp.domain")
    # Una vez generado dicho script, podemos usar su contenido para ejeuctarlo dentro de MySQL y así crear las tablas y sus relaciones en la base de datos
    # Nota: Antes de arrancar la aplicación Spring Boot para generar el script, si tenemos una clase Bootstrap(En este caso "RecipeBootstrap.java") para la carga de datos en las tablas de la base de datos, comentar temporalmente la anotación @Component para que no se cree un bean de esa clase dentro del contexto de Spring porque dará fallos sobre la no existencia de tablas en la base de datos. Una vez generado el script, volvemos a descomentar la anotación @Component en esa clase
    # Estas propiedades sólo son para generar el script, es decir, una vez generado el script, comentar estas propiedades. Cada vez que se quiera generar uno nuevo, volver a descomentar estar propiedades
    #properties:
      #javax:
        #persistence:
          #schema-generation:
            #scripts:
              #action: create
              #create-target: guru_database_create.sql
              #create-source: metadata
            
              
              